name: Variable secret demo

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NAME: ${{ secrets.NAME }} # make it available as $API_KEY
        steps:
            - name: Use the secret
              run: echo "HELLOOO $NAME"
