name: Variable secret demo

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            API_KEY: ${{ secrets.API_KEY }} # make it available as $API_KEY
        steps:
            - name: Use the secret
              run: echo "API key is $API_KEY"
